parent(lakhan,sunil).
parent(lakhan,anil).
parent(rama,sunil).
parent(rama,anil).
parent(lakhan,suman).
parent(rama,suman).
parent(sukhdevi,pratibha).
parent(rameshuwar,pratibha).
parent(sunil,priyanka).
parent(sunil,nisha).
parent(sunil,avnish).
parent(sunil,yogesh).
parent(sunil,karanveer).
parent(sunil,kamal).
parent(meera,priyanka).
parent(meera,nisha).
parent(meera,avnish).
parent(meera,yogesh).
parent(meera,karanveer).
parent(meera,kamal).
spouse(anil,pratibha).
spouse(rameshuwar,sukhdevi).
spouse(lakhan,rama).
spouse(sunil,meera).
male(sunil).
male(anil).
male(avnish).
male(rameshwar).
male(karanveer).
male(yogesh).
male(kamal).
male(lakhan).
female(pratibha).
female(suman).
female(sukhdevi).
female(rama).
female(meera).
female(priyanka).
female(nisha).
father(X,Y):-parent(X,Y),male(X).
mother(X,Y):-parent(X,Y),female(X).
grandfather(X,Y):-father(X,Z),parent(Z,Y).
grandmother(X,Y):-mother(X,Z),parent(Z,Y).
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X),X\==Y.
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X),X\==Y.
husband(X,Y):-spouse(X,Y),male(X).
wife(Y,X):-spouse(X,Y),female(Y).
child(X,Y):-parent(Y,X).
son(X,Y):-parent(Y,X),male(X).
daughter(X,Y):-parent(Y,X),female(X).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandchild(X,Y):-parent(Y,Z),parent(Z,X).
grandson(X,Y):-parent(Y,Z),parent(Z,X),male(X).
granddaughter(X,Y):-parent(Y,Z),parent(Z,X),female(X).
cousin(X,Y):- grandparent(Z,X),grandparent(Z,Y),X\==Y.
ancestor(X,Z):-parent(X,Z). 
ancestor(X,Z):-parent(X,Y),ancestor(Y,Z).
siblings(X,Y):-parent(Z,X),parent(Z,Y).
niece(X,Y) :- female(X),parent(Z,X),sameparent(Z,Y),Z \= Y.
uncle(X,Z):-brother(X,Y),parent(Y,Z).
aunt(X,Z):-brother(A,Y),wife(X,A),parent(Y,Z).
nephew(X,Z):-parent(Y,X),sister(Z,Y).
